apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template: #pod identification
      metadata:
         labels:
            app: mongodb
      spec:
        containers:
        - name: mongodb
          image: mongo:3.6.5-jessie
          volumeMounts:
            - name:  mongo-persistent-storage
              mountPath: /data/db
          volumes:
            - name: mongo-persistent-storage





---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  ports:
    - name: mongodb-port
      port: 2707
  selector:
      app: mongodb
  type: ClusterIP