apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: nodelocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi






---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-local-storage
spec:
   storageClassName: nodelocalstorage
   capacity:
     storage: 10Gi
   accessModes:
    - ReadWriteOnce
   hostPath:
    path: /mnt/data/mongodbvol
    type: DirectoryOrCreate

